
covid19:
  outputs:

    dev:
      type: postgres
      threads: 2
      host: localhost
      port: 5432
      user: postgres
      pass: password
      dbname: postgres
      schema: public

    prod:
      type: postgres
      threads: 2
      host: localhost
      port: 5432
      user: postgres
      pass: password
      dbname: postgres
      schema: public

  target: dev
