[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Sotatek-HaiHo", email = "hai.ho@sotatek.com"},
]
dependencies = [
    "dagster-dbt>=0.18.6",
]
requires-python = ">=3.10"
license = {text = "MIT"}
